### ISSUE TITLE
Change "Read" / "Unread" to "Viewed" / "Not Viewed" in notifications

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#177]
From the FOSSIL team:

>  Instead of “Read / Unread” terms for notifications, change terms to “Viewed / Not Viewed” → people are clicking on “Read” thinking it will allow them to read the message or comment, so this current language is confusing

**Comment by shanebp** [comment]
Done. 
For speed of task completion, done via a filter function in [theme]/functions.php
This really should be done via a language file.
If there are a lot of label changes, that's the approach to take.

**Comment by epoirier** [comment]
Under the Actions column in the Notifications table it still shows "Read" instead of "Viewed".  Actually, in the table I think the label should be "Mark as Viewed" and "Mark as Not Viewed".  Just "Viewed" and "Not Viewed" are kind of confusing.

**Comment by epoirier** [comment]
![image](https://cloud.githubusercontent.com/assets/643301/9212667/edc43994-4058-11e5-995f-fc17fd8b1d3e.png)

**Comment by shanebp** [comment]
Ready for another review.
